version: "3.1"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  #Uncomment if want a UI admin db ready to go
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
